# -*- coding: utf-8 -*-
"""physics_informed_q2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wHsktwE8l5s-u5AoF6x84V6unSIlctB-
"""

import torch
import numpy as np
import matplotlib.pyplot as plt
import utilities_q2

class PhysicsInformedBarModel:
    """A class used for the definition of Physics Informed Models for one dimensional bars."""

    def __init__(self, E, A, L, u0, u1, dist_load):
        """Construct a PhysicsInformedBar model"""
        self.E = E
        self.A = A
        self.L = L
        self.x = utilities_q2.generate_grid_1d(L)
        self.u0 = u0
        self.u1 = u1
        self.dist_load = dist_load
        self.model = utilities_q2.build_model(1,[47,41],1)
        self.differential_equation_loss_history = None
        self.boundary_condition_loss_history = None
        self.total_loss_history = None
        self.optimizer = None

    def get_displacements(self, x):
        """Get displacements."""
        u = self.model(x)   # predict
        return u

    def costFunction(self, x, u_pred):
        """Compute the cost function."""
        # Differential equation loss (f)
        differential_equation_loss = utilities_q2.get_derivative(utilities_q2.get_derivative(self.E(x)*self.A(x)*utilities_q2.get_derivative(utilities_q2.get_derivative(u_pred,x,1),x,1),x,1),x,1) + self.dist_load
        differential_equation_loss = torch.sum(differential_equation_loss ** 2).view(1)

        # Boundary condition loss initialization
        boundary_condition_loss = 0

        # Sum over dirichlet boundary condition losses
        boundary_condition_loss += (u_pred[0] - self.u0[0]) ** 2
        boundary_condition_loss += (u_pred[-1] - self.u0[1]) ** 2

        # Sum over neuman boundary condition losses
        boundary_condition_loss += (utilities_q2.get_derivative(u_pred,x,1)[0] -self.u1[0])**2
        boundary_condition_loss += (utilities_q2.get_derivative(u_pred,x,1)[-1] -self.u1[1])**2

        return differential_equation_loss, boundary_condition_loss

    def closure(self):
        """Calculation of training error and gradient"""
        self.optimizer.zero_grad()
        u_pred = self.get_displacements(self.x)
        loss = self.costFunction(self.x, u_pred)
        loss = loss[0] + loss[1]
        loss.backward(retain_graph=True)
        return loss

    def train(self, epochs, optimizer='Adam', **kwargs):
        """Train the model."""
        # Set optimizer
        if optimizer=='Adam':
            self.optimizer = torch.optim.Adam(self.model.parameters(), **kwargs)
        
        elif optimizer=='LBFGS':
            self.optimizer = torch.optim.LBFGS(self.model.parameters(), **kwargs)

        # Initialize history arrays
        self.differential_equation_loss_history = np.zeros(epochs)
        self.boundary_condition_loss_history = np.zeros(epochs)
        self.total_loss_history = np.zeros(epochs)

        # Training loop
        for i in range(epochs):
            # Predict displacements
            u_pred = self.get_displacements(self.x)

            # Cost function calculation
            differential_equation_loss, boundary_condition_loss = self.costFunction(self.x, u_pred)

            # Total loss
            total_loss = differential_equation_loss + boundary_condition_loss

            # Add energy values to history
            self.differential_equation_loss_history[i] += differential_equation_loss
            self.boundary_condition_loss_history[i] += boundary_condition_loss
            self.total_loss_history[i] += total_loss

            # Print training state
            self.print_training_state(i, epochs)

            # Update parameters (Neural network train)
            self.optimizer.step(self.closure)

    def print_training_state(self, epoch, epochs, print_every=100):
        """Print the loss values of the current epoch in a training loop."""

        if epoch == 0 or epoch == (epochs - 1) or epoch % print_every == 0 or print_every == 'all':
            # Prepare string
            string = "Epoch: {}/{}\t\tDifferential equation loss = {:2f}\t\tBoundary condition loss = {:2f}\t\tTotal loss = {:2f}"

            # Format string and print
            print(string.format(epoch, epochs - 1, self.differential_equation_loss_history[epoch],
                                self.boundary_condition_loss_history[epoch], self.total_loss_history[epoch]))

    def plot_training_history(self, yscale='log'):
        """Plot the training history."""

        # Set up plot
        fig, ax = plt.subplots(figsize=(4,3))
        ax.set_title("Cost function history")
        ax.set_xlabel("Epochs")
        ax.set_ylabel("Cost function C")
        plt.yscale(yscale)

        # Plot data
        ax.plot(self.total_loss_history, 'k', linewidth=2, label="Total cost")
        ax.plot(self.differential_equation_loss_history, color='silver', linestyle='--', linewidth=2, label="Differential equation loss")
        ax.plot(self.boundary_condition_loss_history, color='r', linestyle='-.', linewidth=2, label="Boundary condition loss")
        

        ax.legend()
        fig.tight_layout()
        plt.show()